# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev

pool:
  vmImage: ubuntu-latest

# variables:
#   ${{ if eq(variables['Build.SourceBranchName'], 'refs/heads/dev') }}:
#     myVariable: 'developValue'
#   ${{ if eq(variables['Build.SourceBranchName'], 'refs/heads/main') }}:
#     myVariable: 'mainValue'


steps:
- script: |
    sam build
    ls .aws-sam/
  displayName: 'Sam build'

- task: CopyFiles@2
  inputs:
    Contents: |
      *.yaml
      *.toml
    TargetFolder: '$(build.artifactstagingdirectory)'
    CleanTargetFolder: true
    ignoreMakeDirErrors: true
- task: CopyFiles@2
  inputs:
    SourceFolder: '.aws-sam'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)/.aws-sam'
    CleanTargetFolder: true
    ignoreMakeDirErrors: true

- publish: $(build.artifactstagingdirectory)
  artifact: SamArtifacts

# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'echo "##vso[build.addbuildtag]dev"'


